[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.0" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "2.2.0" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version = "2.2.0" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = "2.2.0" }
spring-boot = { id = "org.springframework.boot", version = "3.5.4" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
flyway = { id = "org.flywaydb.flyway", version = "11.11.0" }
graalvm-buildtools-native = { id = "org.graalvm.buildtools.native", version = "0.11.0" }

[libraries]
springdoc-openapi-starter-mvc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version = "2.8.9" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name="jackson-datatype-jsr310", version = "2.19.2" }
kostest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version = "5.9.1" }
