[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.3.0" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "2.3.0" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version = "2.3.0" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = "2.3.0" }
spring-boot = { id = "org.springframework.boot", version = "3.5.7" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
flyway = { id = "org.flywaydb.flyway", version = "11.20.0" }
graalvm-buildtools-native = { id = "org.graalvm.buildtools.native", version = "0.11.3" }

[libraries]
springdoc-openapi-starter-mvc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version = "2.8.14" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name="jackson-datatype-jsr310", version = "2.20.1" }
kostest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version = "6.0.7" }
