name: Updates plugins

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  update-gradle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Run dependency update script
        run: make deps-gradle-update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update gradle
          branch: update-gradle
          title: 'Update gradle'
          body: |
            This pull request updates the following dependencies:
            - Current gradle updates
          labels: dependencies
